add @mesonbuild
cade-vs/vstring pull request #10
Opened 2023-02-15 17:24 UTC by andy5995

2023-02-15 17:49 UTC, andy5995 commented
All 6 meson jobs are passing.

2023-02-15 19:45 UTC, eli-schwartz requested changes

2023-02-15 19:45 UTC, eli-schwartz commented on meson.build
> +endforeach
```suggestion
add_project_arguments(cxx.get_supported_arguments(extra_flags), language: 'cpp')
```

Available since 0.43.0

2023-02-15 19:45 UTC, eli-schwartz commented on meson.build
> +  soversion : '0',
By the way :) the default soversion is "split the version according to dots, and use the first component".

2023-02-15 19:45 UTC, eli-schwartz commented on meson.build
> +dep_vstring = declare_dependency(link_with : buildtarget)
You probably also want to add an `include_directories('.')`

2023-02-15 19:45 UTC, eli-schwartz commented on meson.build
> +    case,
You'll end up creating executables such as `test_test.cpp.exe` and `test_wtest.cpp.exe`, maybe you should split the test case and only take the part before the dot? Or alternatively, foreach over the name without the extension and list the source file as `case+'.cpp'`?

2023-02-16 00:25 UTC, andy5995 commented
Thanks for the suggestions @eli-schwartz !

2023-02-16 00:26 UTC, andy5995 commented
@cade-vs If you decide to use this, I'd recommend using [squash-merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests)

2023-04-19 05:05 UTC, closed without merging